<?xml version="1.0"?>


<robot name="cepheus" xmlns:xacro="http://www.ros.org/wiki/xacro">
	<xacro:include filename="$(find cepheus_description)/urdf/cepheus.gazebo" />
	<xacro:include filename="$(find cepheus_description)/urdf/materials.xacro" />
	<xacro:include filename="$(find cepheus_description)/urdf/inertial_macros.xacro"/>
	<xacro:property name="camera_link" value="0.05" /> <!-- Size of square 'camera' box -->
	<!-- <xacro:property name="arm" value="0.37" />
	<xacro:property name="forearm" value="0.286" />
	<xacro:property name="gripper" value="0.0672" /> -->
	<xacro:property name="base_radius" value="0.2" />
	<xacro:property name="y" value="0.02" />
	<!-- <xacro:property name="arm_length" value="0.5" />
	<xacro:property name="forearm_length" value="0.5" />
	<xacro:property name="gripper_length" value="0.125" />
	<xacro:property name="base_mass" value="53" />
	<xacro:property name="arm_mass" value="1" />
	<xacro:property name="forearm_mass" value="0.5" />
	<xacro:property name="gripper_mass" value="0.1" />
	<xacro:property name="base_inertia" value="${(1/2)*base_mass*base_radius*base_radius}" />
	<xacro:property name="arm_inertia" value="${(1/12)*arm_mass*(arm_length*arm_length+y*y)}" />
	<xacro:property name="forearm_inertia" value="${(1/12)*forearm_mass*(forearm_length*forearm_length+y*y)}" />
	<xacro:property name="gripper_inertia" value="${(1/12)*gripper_mass*(gripper_length*gripper_length+y*y)}" /> -->
	<!-- gia sygkrish me simscape 29/7 -->
	<xacro:property name="arm_length" value="0.37" />
	<xacro:property name="forearm_length" value="0.368" />
	<!-- <xacro:property name="gripper_length" value="0.0411" /> -->
	<xacro:property name="gripper_length" value="0.0822" />
	<xacro:property name="base_mass" value="53" />
	<xacro:property name="arm_mass" value="0.2314" />
	<xacro:property name="forearm_mass" value="0.1" />
	<xacro:property name="gripper_mass" value="4.6" />
	<xacro:property name="base_inertia" value="1.06" />
	<xacro:property name="arm_inertia" value="0.0026476" />
	<xacro:property name="forearm_inertia" value="0.0011318" />
	<!-- <xacro:property name="gripper_inertia" value="${9.61/100000}" /> -->
	<xacro:property name="gripper_inertia" value="${2.73/1000}" />
	<xacro:property name="joint_damping" value="1" />
	<xacro:property name="joint_friction" value="1" />
	<xacro:property name="joint_limit" value="3.14" />
	<xacro:property name="joint_velocity" value="100000" />	
	<xacro:property name="joint_effort" value="100000" />


	<!-- gia test epitagynshs: need fixing -->
	<!-- <xacro:property name="gripper_length" value="0.1" />
	<xacro:property name="gripper_mass" value="23.0769" /> 
	<xacro:property name="gripper_inertia" value="0.02" /> -->








	
	<link name="world">
		<!-- <joint name="world_joint" type="continuous">
			<axis xyz="0 0 1"/>
			<parent link="world"/>
			<origin rpy="0 0 0" xyz="0 0 0"/>
			<child link="cepheus"/>
			<dynamics damping="0" friction="0"/>
		</joint> -->
	</link>
    	<joint name="p1_joint" type="prismatic">
		<parent link="world"/>
		<child link="p1"/>
		<axis xyz="1 0 0"/>
		<limit lower="-100" upper="100" effort="${joint_effort}" velocity="${joint_velocity}"/>
		<dynamics damping="${joint_damping}" friction="${joint_friction}"/>
	</joint>
	<link name="p1">
		<inertial>
			<origin
				xyz="0.0 0.0 0.0"
				rpy="0.0 0.0 0.0" />
			<mass value="0.01" />
			<inertia
				ixx="1e-2"
				ixy="0.000001"
				ixz="0.000001"
				iyy="1e-2"
				iyz="0.000001"
				izz="1e-2" />
		</inertial>
	</link>
	<gazebo reference="p1">
		<mu1>0</mu1>
		<mu2>0</mu2>
	</gazebo>
	<transmission name="lin1">
		<type>transmission_interface/SimpleTransmission</type>
		<joint name="p1_joint">
			<hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
		</joint>
		<actuator name="lin_motor1">
			<hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
			<mechanicalReduction>1</mechanicalReduction>
		</actuator>
	</transmission>
	<joint name="p2_joint" type="prismatic">
		<parent link="p1"/>
		<child link="p2"/>
		<axis xyz="0 1 0"/>
		<limit
			lower="-100"
			upper="100"
			effort="${joint_effort}"
			velocity="${joint_velocity}"/>
		<dynamics
			damping="${joint_damping}"
			friction="${joint_friction}"/>
	</joint>
	<link name="p2">
		<inertial>
			<origin
				xyz="0.0 0.0 0.0"
				rpy="0.0 0.0 0.0" />
			<mass value="0.01" />
			<inertia
				ixx="1e-2"
				ixy="0.000001"
				ixz="0.000001"
				iyy="1e-2"
				iyz="0.000001"
				izz="1e-2" />
		</inertial>
		<surface>
			<friction>
				<ode>
					<mu>0</mu>
					<mu2>0</mu2>
					<fdir1>0 1.0 0</fdir1>
					<implicit_spring_damper>true</implicit_spring_damper>
				</ode>
			</friction>
		</surface>
	</link>
	<gazebo reference="p2">
		<mu1>0</mu1>
		<mu2>0</mu2>
	</gazebo>
	<transmission name="lin2">
		<type>transmission_interface/SimpleTransmission</type>
		<joint name="p2_joint">
			<hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
		</joint>
		<actuator name="lin_motor2">
			<hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
			<mechanicalReduction>1</mechanicalReduction>
		</actuator>
	</transmission>
	<joint name="left_wrist_joint" type="continuous">
		<axis xyz="0 0 1"/>
		<parent link="p2"/>
		<origin rpy="0 0 0" xyz="0 0 0"/>
		<child link="left_grip"/>
		<dynamics damping="${joint_damping}" friction="${joint_friction}"/>
	</joint>
	<transmission name="tran1">
		<type>
			transmission_interface/SimpleTransmission</type>
		<joint name="left_wrist_joint">
			<hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
		</joint>
		<actuator name="motor1">
			<hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
			<mechanicalReduction>1</mechanicalReduction>
		</actuator>
	</transmission>

	<link name="left_grip">
		<inertial>
			<origin
				xyz="${gripper_length/2} 0 0"
				rpy="0 0 0" />
			<mass value="${gripper_mass}" />
			<inertia
				ixx="0.0001"
				ixy="0.0001"
				ixz="0.0001"
				iyy="0.0001"
				iyz="0.0001"
				izz="${gripper_inertia}" />
		</inertial>
		<visual>
			<origin
				xyz="${gripper_length/2} 0 0"
				rpy="0 0 0" />
			<geometry>
				<box size="${gripper_length} 0.02 0.02"/>
			</geometry>
			<material name="LightGrey"/>
		</visual>
		<collision>
			<origin
				xyz="${gripper_length/2} 0 0"
				rpy="0 0 0" />
			<geometry>
				<box size="${gripper_length} 0.02 0.02"/>
			</geometry>
			<!-- <surface>
				<friction>
					<ode>
						<mu>0</mu>           
						<mu2>0</mu2>        
					</ode>
				</friction>
			</surface> -->
		</collision>
	</link> 
    <gazebo reference="left_grip">
		<mu1>0</mu1>
		<mu2>0</mu2>
	</gazebo>
	<joint name="final_joint" type="revolute">
		<parent link="left_grip"/>
		<child link="final_link"/>
		<origin
			xyz="${gripper_length} 0 0"
			rpy="0 0 0 " />
		<axis xyz="0 1 0"/>
		<limit lower="-1" upper="1" effort="${joint_effort}" velocity="${joint_velocity}"/>
		<dynamics damping="1" friction="1"/>
	</joint>
	<link name="final_link">
		<inertial>
			<origin
				xyz="0.0 0.0 0.0"
				rpy="0.0 0.0 0.0" />
			<mass value="0.0001" />
			<inertia
				ixx="1e-7"
				ixy="0.00001"
				ixz="0.00001"
				iyy="1e-7"
				iyz="0.00001"
				izz="1e-7" />
		</inertial>
	</link>

	<transmission name="tran4">
		<type>transmission_interface/SimpleTransmission</type>
		<joint name="left_wrist_joint">
			<hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
		</joint>
		<actuator name="motor4">
			<hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
			<mechanicalReduction>1</mechanicalReduction>
		</actuator>
	</transmission>
	<gazebo reference="left_wrist_joint">
		<provideFeedback>true</provideFeedback>
		<!-- <sensor name="force_torque" type="force_torque">
          <update_rate>30</update_rate>
    	</sensor> -->
	</gazebo>
    <gazebo>
		<plugin name="ft_sensor" filename="libgazebo_ros_ft_sensor.so">
			<updateRate>0</updateRate>   <!--poly shmantiko na einai 0, allios kanei bug!!!!(nikhforos)-->
			<topicName>ft_sensor_topic</topicName>
			<jointName>left_wrist_joint</jointName>
			<noise>
          		<type>gaussian</type>
          		<mean>0.0</mean>
          		<stddev>0.0003</stddev> <!-- change this to simulate noise --> 
        	</noise>
		</plugin>
	</gazebo>



	<gazebo reference="left_grip">
		<sensor name="imu_sensor" type="imu">
			<always_on>true</always_on>
			<update_rate>100</update_rate>
			<visualize>true</visualize>
			<topic>imu_sensor_topic</topic>
			<plugin filename="libgazebo_ros_imu_sensor.so" name="imu_plugin">
				<topicName>imu</topicName>
				<bodyName>left_grip</bodyName>
				<updateRateHZ>10.0</updateRateHZ>
				<gaussianNoise>0.0</gaussianNoise>
				<xyzOffset>0 0 0</xyzOffset>
				<rpyOffset>0 0 0</rpyOffset>
				<frameName>left_grip</frameName>
				<initialOrientationAsReference>false</initialOrientationAsReference>
			</plugin>
			<!-- <pose>0 0 0 0 0 0</pose> -->
		</sensor>
  </gazebo>	

</robot>