controller_list:
  - name: fake_left_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - left_shoulder
      - left_elbow
      - reaction_wheel_joint
initial:  # Define initial robot poses per group
  - group: left_arm
    pose: test1