cepheus:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  # Position Controllers ---------------------------------------
  group_torque_controller:
    type: effort_controllers/JointGroupEffortController
    joints: 
      - left_shoulder
      - left_elbow
      - left_wrist
      - reaction_wheel_joint
    left_shoulder:
      pid: {p: 10.0, i: 0.1, d: 1.0}
    left_elbow:
      pid: {p: 10.0, i: 0.1, d: 1.0}
    reaction_wheel_joint:
      pid: {p: 1.0, i: 0.1, d: 0.001}
    left_wrist:
      pid: {p: 10.0, i: 0.1, d: 1.0}

  
  # CartesianImpedance_trajectory_controller:
  #   type: cartesian_impedance_controller/CartesianImpedanceController
  #   joints:                               # Joints to control
  #     - left_shoulder
  #     - left_elbow
  #     - reaction_wheel_joint
  #     # - left_wrist
  #   end_effector: left_forearm          # Link to control arm in
  #   update_frequency: 500                 # Controller update frequency in Hz
  #   # Optional parameters - the mentioned values are the defaults
  #   dynamic_reconfigure: false             # Starts dynamic reconfigure server
  #   handle_trajectories: true             # Accept traj., e.g. from MoveIt
  #   robot_description: /robot_description # In case of a varying name
  #   wrench_ee_frame: left_forearm         # Default frame for wrench commands
  #   delta_tau_max: 1.0                    # Max. commanded torque diff between steps in Nm
  #   filtering:                            # Update existing values (0.0 1.0] per s
  #     nullspace_config: 0.1               # Nullspace configuration filtering
  #     pose: 0.1                           # Reference pose filtering
  #     stiffness: 0.1                      # Cartesian and nullspace stiffness
  #     wrench: 0.1                         # Commanded torque
  #   verbosity:
  #     verbose_print: true                # Enables additional prints
  #     state_msgs: true                   # Messages of controller state
  #     tf_frames: true                    # Extra tf frames

  # new controllers

  # #Position Controllers ---------------------------------------
  # p1_position_controller:
  #  type: effort_controllers/JointPositionController
  #  joint: p1_joint
  #  pid: {p: 50.0, i: 0.1, d: 30.0}
  
  # #Position Controllers ---------------------------------------
  # p2_position_controller:
  #  type: effort_controllers/JointPositionController
  #  joint: p2_joint
  #  pid: {p: 50.0, i: 0.1, d: 30.0}
