# cepheus:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  # Position Controllers ---------------------------------------
  left_shoulder_effort_controller:
    type: effort_controllers/JointEffortController
    joint: left_shoulder
    pid: {p: 10.0, i: 0.1, d: 1.0}
    # pid: {p: 1.0, i: 0.1, d: 1.0}
  # Position Controllers ---------------------------------------
  left_elbow_effort_controller:
    type: effort_controllers/JointEffortController
    joint: left_elbow
    pid: {p: 10.0, i: 0.1, d: 1.0}
  left_wrist_effort_controller:
    type: effort_controllers/JointEffortController
    joint: left_wrist
    pid: {p: 10.0, i: 0.1, d: 1.0}
    # pid: {p: 1.0, i: 0.1, d: 1.0}
  # Velocity Controllers ---------------------------------------
  reaction_wheel_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: reaction_wheel_joint
    pid: {p: 1.0, i: 0.1, d: 0.001}