cepheus:  
  CartesianImpedance_trajectory_controller:
    type: cartesian_impedance_controller/CartesianImpedanceController
    joints:                               # Joints to control
      - left_shoulder
      - left_elbow
      - reaction_wheel_joint
    end_effector: left_grip           # Link to control arm in
    update_frequency: 500                 # Controller update frequency in Hz
    # Optional parameters - the mentioned values are the defaults
    dynamic_reconfigure: true             # Starts dynamic reconfigure server
    handle_trajectories: true             # Accept traj., e.g. from MoveIt
    robot_description: /robot_description # In case of a varying name
    wrench_ee_frame: left_grip         # Default frame for wrench commands
    delta_tau_max: 1.0                    # Max. commanded torque diff between steps in Nm
    filtering:                            # Update existing values (0.0 1.0] per s
      nullspace_config: 0.1               # Nullspace configuration filtering
      pose: 0.1                           # Reference pose filtering
      stiffness: 0.1                      # Cartesian and nullspace stiffness
      wrench: 0.1                         # Commanded torque
    verbosity:
      verbose_print: false                # Enables additional prints
      state_msgs: false                   # Messages of controller state
      tf_frames: false                    # Extra tf frames